spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
chaos:
  monkey:
    enabled: true 
    watcher:
      controller: true
      restController: true
      service: true
      repository: true
      component: true
    assaults:
      level: 5
      exceptionsActive: true
      memoryActive: true
      latencyActive: true
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      killApplicationActive: true
